### ISSUE TITLE
script error @qb-blackmarket/client/main.lua:94: attempt to index a nil value (field '?')

### ISSUE THREAD

**Issue by primoixi** [arabcodingteam/qb-blackmarket#2]
@qb-blackmarket/client/main.lua:94: attempt to index a nil value (field '?')
>handler (@qb-blackmarket/client/main.lua:94)
>fn (@qb-target/client.lua:922)

**Comment by krrm1** [comment]
make sure the items in small capital or it in the items shared

**Comment by primoixi** [comment]
Thanks for update working fine now
