### ISSUE TITLE
How to change to where if inventory is full cannot buy

### ISSUE THREAD

**Issue by gigitygamer** [arabcodingteam/qb-blackmarket#3]
Hey, so if people buy out of crazy jack and their inventory is full. it will still charge them but not give them the items.. cant we fix that?

**Comment by krrm1** [comment]
hello , i will update soon and fix it

**Comment by ENoir420** [comment]
Hi @krrm1 i fork it and i personalize your script, if you could tell me how could i share it with you here on GitHub you can see the changes that i made

**Comment by krrm1** [comment]
Just but my account down the readme

**Comment by ENoir420** [comment]
I've to do what?

**Comment by krrm1** [comment]
update is ready
